# Overview of Subsetting in Pandas 



**TABLE OF CONTENTS**

- What is an index?
- How to subset first N rows based on their position index?
- Can we change the index?
- will the index be always numeric?
- How to subset the data based on label of index?
- Can we reset the index?
- How to subset the data based on a value of a column?

READ THE DATA 

- In this notebook, we are going to use big mart sales that we have used previously. It is stored in the folder name datasets.

In [0]:
#import the pandas library
%pip install pandas==1.5.2

Python interpreter will be restarted.
Requirement already satisfied: pandas==1.5.2 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-0c590ea5-a074-4722-bdc4-fe8b5cdc99ff/lib/python3.9/site-packages (1.5.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /databricks/python3/lib/python3.9/site-packages (from pandas==1.5.2) (2.8.2)
Requirement already satisfied: numpy>=1.20.3 in /databricks/python3/lib/python3.9/site-packages (from pandas==1.5.2) (1.21.5)
Requirement already satisfied: pytz>=2020.1 in /databricks/python3/lib/python3.9/site-packages (from pandas==1.5.2) (2021.3)
Requirement already satisfied: six>=1.5 in /databricks/python3/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas==1.5.2) (1.16.0)
Python interpreter will be restarted.

In [0]:
import pandas as pd
pd.__version__

Out[1]: '1.5.2'

In [0]:
dbutils.fs.cp("dbfs:/FileStore/ml/datasets/big_mart_sales.csv", "file:///tmp/datasets/big_mart_sales.csv")

Out[2]: True

In [0]:
with open('/tmp/datasets/big_mart_sales.csv', 'r') as f:
    text = f.readline()
    print(text)

Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales

In [0]:
#read the big mart sales data

data = pd.read_csv('file:///tmp/datasets/big_mart_sales.csv')

In [0]:
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [0]:
data.tail()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

- You can see the index object by Dataframe.index

In [0]:
# index of the dataframe

data.index

Out[7]: RangeIndex(start=0, stop=8523, step=1)

**So, In this case, we have the numeric index value start from 0 and 8523.**

In [0]:
# no of rows and columns in the data
data.shape

Out[8]: (8523, 12)

In [0]:
# column index 

data.columns

Out[9]: Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales'],
      dtype='object')

####HOW TO SUBSET 'N ROWS' BASED ON THE POSITION INDEX?

In [0]:
# views the top rows of the data
data.head(10)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
6,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
7,FDP10,NaN,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636
8,FDH17,16.200,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,NaN,Tier 2,Supermarket Type1,1076.5986
9,FDU28,19.200,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,NaN,Tier 2,Supermarket Type1,4710.5350

**CAN WE CHANGE THE INDEX?**

The answer is Yes, We can change the index, Let's see how?

**Create a random list of 8523 numbers and set it as the index**

In [0]:
# create random list

import random 

random_list = [random.randint(1, 8523) for i in range(8523)]

In [0]:
random_list

Out[12]: [3184,
 7490,
 3927,
 1730,
 4842,
 6444,
 1758,
 1062,
 3723,
 6385,
 919,
 1937,
 4755,
 3228,
 4060,
 2694,
 2650,
 3370,
 1068,
 7895,
 4669,
 5072,
 6644,
 4881,
 1404,
 1056,
 1389,
 320,
 5497,
 7270,
 326,
 2040,
 1328,
 7194,
 6199,
 3925,
 5782,
 4999,
 7311,
 4350,
 586,
 7188,
 5406,
 6857,
 3842,
 4443,
 1630,
 5376,
 5517,
 356,
 6578,
 7082,
 5561,
 3599,
 4533,
 105,
 6570,
 4096,
 8097,
 4397,
 2809,
 374,
 2487,
 5587,
 8522,
 6710,
 3763,
 1523,
 2525,
 6348,
 1204,
 4578,
 4327,
 1350,
 4791,
 1350,
 5748,
 6800,
 442,
 2344,
 3776,
 7822,
 5933,
 1342,
 5104,
 1856,
 4472,
 420,
 6055,
 5197,
 99,
 1383,
 8468,
 8137,
 2623,
 7176,
 1873,
 6453,
 4115,
 2076,
 3264,
 8100,
 248,
 448,
 611,
 6587,
 2849,
 3712,
 7623,
 7210,
 5740,
 2408,
 7755,
 7588,
 5257,
 8294,
 5087,
 519,
 6330,
 1877,
 1020,
 2102,
 1408,
 6585,
 4314,
 851,
 1533,
 4284,
 2660,
 2239,
 1963,
 6938,
 8049,
 3359,
 2104,
 7699,
 4926,
 5360,
 8034,
 5374,
 4446,
 7260,
 586,
 2001,
 2727,
 7796,
 5615,
 4791,
 1287,
 1064,
 5068,
 6289,
 6247,
 4055,
 6655,
 7802,
 4280,
 5904,
 1971,
 5646,
 7936,
 1404,
 1740,
 238,
 2558,
 3289,
 7498,
 7330,
 2374,
 670,
 4602,
 2109,
 5184,
 2985,
 832,
 1350,
 7543,
 2310,
 3044,
 7765,
 6280,
 4620,
 6232,
 2117,
 744,
 3306,
 3448,
 7887,
 6403,
 5978,
 7864,
 2214,
 6274,
 2875,
 4776,
 4991,
 7141,
 8215,
 2331,
 4366,
 2228,
 8124,
 151,
 4492,
 7051,
 4124,
 6320,
 382,
 8070,
 665,
 159,
 3970,
 4379,
 6212,
 5307,
 5052,
 436,
 8263,
 5713,
 7518,
 4700,
 1904,
 3188,
 48,
 237,
 791,
 4598,
 7886,
 6697,
 8365,
 5164,
 4778,
 4954,
 1715,
 7959,
 293,
 4396,
 7105,
 6093,
 5275,
 5783,
 1670,
 2124,
 1161,
 1759,
 4200,
 2166,
 4320,
 1765,
 5875,
 6541,
 8111,
 4535,
 3645,
 1358,
 6838,
 5450,
 3818,
 6513,
 7609,
 5350,
 734,
 6616,
 3807,
 4921,
 4878,
 3030,
 2256,
 1509,
 4763,
 5098,
 2092,
 60,
 4296,
 8224,
 1420,
 2220,
 6994,
 3736,
 3196,
 5896,
 6260,
 872,
 3005,
 2810,
 5967,
 4016,
 5897,
 497,
 5878,
 4515,
 4232,
 3987,
 1917,
 6618,
 5023,
 363,
 1671,
 6170,
 6916,
 2858,
 6839,
 8044,
 1464,
 7915,
 2516,
 1488,
 3409,
 3443,
 683,
 754,
 8242,
 6088,
 6311,
 369,
 3347,
 1221,
 4623,
 351,
 5419,
 5191,
 473,
 7591,
 4725,
 2821,
 2119,
 8251,
 5310,
 2602,
 7492,
 470,
 910,
 598,
 1565,
 7755,
 5591,
 4748,
 4447,
 2971,
 6847,
 3492,
 6332,
 204,
 4064,
 5409,
 433,
 2684,
 500,
 7771,
 6581,
 4555,
 1484,
 6011,
 462,
 520,
 3092,
 2524,
 4313,
 4228,
 7401,
 6042,
 6583,
 696,
 8047,
 7422,
 3150,
 5618,
 4634,
 1626,
 2303,
 8034,
 4392,
 906,
 888,
 5814,
 1914,
 5682,
 2113,
 7369,
 8313,
 3628,
 8313,
 7886,
 1807,
 4539,
 5054,
 4785,
 6785,
 6186,
 760,
 6726,
 2353,
 1964,
 1775,
 4587,
 7040,
 623,
 2068,
 1552,
 7466,
 1107,
 5965,
 6361,
 5339,
 1099,
 8522,
 2140,
 5351,
 7270,
 3622,
 7486,
 752,
 2840,
 7706,
 3780,
 6539,
 4362,
 3107,
 6285,
 1606,
 5805,
 6214,
 645,
 191,
 2794,
 846,
 6841,
 8347,
 4304,
 3025,
 2564,
 6043,
 456,
 5433,
 4104,
 1133,
 3028,
 6957,
 6240,
 379,
 1012,
 6999,
 542,
 2488,
 828,
 5348,
 4280,
 7279,
 2037,
 2902,
 7375,
 5177,
 228,
 6143,
 289,
 3388,
 5694,
 1579,
 4185,
 7371,
 2061,
 1180,
 4651,
 3028,
 3500,
 7990,
 413,
 2209,
 5354,
 6964,
 2152,
 1661,
 3326,
 6898,
 4412,
 7153,
 4824,
 829,
 4628,
 4439,
 3045,
 5831,
 3788,
 4480,
 5726,
 4670,
 3962,
 7781,
 8151,
 6324,
 5559,
 688,
 60,
 5540,
 147,
 3849,
 1121,
 8445,
 3005,
 1022,
 7102,
 2411,
 7961,
 650,
 6192,
 293,
 6885,
 6824,
 3144,
 4775,
 5374,
 6612,
 8162,
 7904,
 4280,
 8309,
 2611,
 1313,
 2993,
 6967,
 2685,
 4588,
 3446,
 401,
 2554,
 6660,
 4914,
 3893,
 6598,
 4649,
 1603,
 5972,
 6665,
 1580,
 618,
 2498,
 2198,
 6639,
 4009,
 5418,
 5501,
 5349,
 2056,
 3115,
 6816,
 7717,
 1686,
 3869,
 1337,
 2121,
 3974,
 2180,
 6474,
 7260,
 2675,
 8215,
 543,
 5122,
 4285,
 1767,
 4915,
 3122,
 1383,
 5230,
 4951,
 5924,
 3813,
 3883,
 4405,
 4189,
 7141,
 1575,
 4563,
 4091,
 4551,
 4368,
 3888,
 5982,
 7488,
 6415,
 2809,
 6964,
 2516,
 3907,
 264,
 4541,
 480,
 4966,
 3786,
 4979,
 6813,
 6148,
 1314,
 107,
 504,
 3291,
 3481,
 4415,
 6067,
 6984,
 6071,
 3212,
 4105,
 1223,
 6737,
 3907,
 1091,
 3843,
 5103,
 6427,
 2775,
 7929,
 688,
 7232,
 627,
 1636,
 4471,
 8125,
 6784,
 2485,
 5482,
 1700,
 2728,
 3561,
 2845,
 7045,
 3870,
 3058,
 5247,
 6862,
 2908,
 1367,
 5604,
 5089,
 1155,
 606,
 7419,
 5047,
 6082,
 842,
 7034,
 6306,
 1528,
 8296,
 1615,
 3916,
 2278,
 126,
 5223,
 6960,
 6348,
 6702,
 3958,
 2342,
 4277,
 6097,
 1868,
 7969,
 1015,
 773,
 6238,
 1811,
 206,
 2157,
 3245,
 1127,
 5346,
 548,
 1116,
 7434,
 7393,
 7287,
 4905,
 5297,
 6071,
 7843,
 5154,
 5659,
 396,
 5963,
 4650,
 4548,
 193,
 2297,
 3417,
 2973,
 5666,
 6300,
 7610,
 8035,
 5795,
 2980,
 5691,
 6540,
 5290,
 3223,
 7433,
 6081,
 1167,
 1367,
 2678,
 4276,
 6583,
 5857,
 6022,
 2626,
 2987,
 1026,
 2472,
 3782,
 4131,
 2477,
 3576,
 5047,
 7936,
 1745,
 5538,
 1673,
 2209,
 3583,
 2721,
 2005,
 1117,
 8024,
 5964,
 8501,
 4611,
 5687,
 4062,
 7298,
 4990,
 4304,
 5542,
 3132,
 7456,
 5426,
 996,
 3663,
 6659,
 6445,
 7311,
 8379,
 7491,
 4421,
 1724,
 581,
 896,
 2494,
 5294,
 2061,
 7079,
 7053,
 1095,
 1863,
 7561,
 816,
 4738,
 4888,
 7320,
 3709,
 5872,
 949,
 2348,
 3963,
 7704,
 8381,
 610,
 1664,
 4120,
 5495,
 6720,
 8511,
 8302,
 8075,
 648,
 2074,
 7029,
 5038,
 4341,
 1447,
 357,
 701,
 4401,
 5915,
 2413,
 4055,
 7604,
 6681,
 6048,
 2404,
 634,
 1705,
 4277,
 6270,
 1151,
 4881,
 5903,
 2884,
 2031,
 7244,
 4417,
 5248,
 5080,
 4720,
 5407,
 8470,
 5715,
 1980,
 4044,
 6166,
 3004,
 821,
 712,
 7135,
 4191,
 2985,
 3396,
 2909,
 679,
 8306,
 1910,
 8447,
 4846,
 3614,
 7828,
 8203,
 6061,
 4572,
 3772,
 4506,
 2051,
 5787,
 5297,
 4515,
 3681,
 7470,
 4613,
 511,
 7715,
 3147,
 6461,
 3994,
 5927,
 1551,
 4581,
 8285,
 233,
 2207,
 4187,
 3817,
 3905,
 6666,
 6409,
 7160,
 26,
 3074,
 5479,
 7440,
 3815,
 4434,
 4735,
 6486,
 3244,
 2482,
 5162,
 7078,
 6345,
 2570,
 8379,
 986,
 1309,
 174,
 3017,
 3607,
 41,
 521,
 1032,
 3118,
 651,
 2139,
 3708,
 6930,
 5075,
 3872,
 385,
 7988,
 5849,
 3549,
 2210,
 1899,
 41,
 2353,
 3896,
 1232,
 627,
 516,
 6316,
 4320,
 1159,
 3427,
 994,
 3112,
 5149,
 5598,
 3703,
 8118,
 8279,
 6153,
 5397,
 3402,
 7390,
 8432,
 6529,
 7528,
 5008,
 5464,
 6784,
 7472,
 6475,
 3820,
 8054,
 4506,
 1775,
 3041,
 2494,
 7865,
 8219,
 8071,
 6498,
 2422,
 3095,
 4850,
 6866,
 3518,
 7591,
 7344,
 7572,
 1272,
 5704,
 5277,
 4519,
 7053,
 2175,
 7482,
 615,
 3292,
 4679,
 760,
 6641,
 3252,
 6724,
 7744,
 6841,
 2776,
 1584,
 2859,
 6749,
 2528,
 6381,
 3120,
 4826,
 6233,
 3167,
 3911,
 8324,
 4297,
 1930,
 4719,
 4255,
 315,
 4989,
 629,
 8329,
 281,
 722,
 3772,
 4522,
 3168,
 1098,
 6671,
 3068,
 6914,
 4434,
 3019,
 1381,
 2748,
 4270,
 7914,
 238,
 7864,
 7329,
 2079,
 6474,
 4533,
 1431,
 5645,
 3624,
 2342,
 6132,
 1997,
 ...]

In [0]:
# set the index

data.index = random_list

In [0]:
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
3184,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
7490,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
3927,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
1730,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4842,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

**Set another coulumn as the index. We will use the set_index function.**

In [0]:
# 1. change the index of the dataframe
# 2. drop=True is used to dropthe column that's set as index
# 3. inplace=True is used to make changes in the original dataframe


data= pd.read_csv('file:///tmp/datasets/big_mart_sales.csv')

data.set_index('Outlet_Establishment_Year', drop=True, inplace=True)

In [0]:
# example of a label based index

data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
Outlet_Establishment_Year,,,,,,,,,,,
1999,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,Medium,Tier 1,Supermarket Type1,3735.1380
2009,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,Medium,Tier 3,Supermarket Type2,443.4228
1999,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,Medium,Tier 1,Supermarket Type1,2097.2700
1998,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,NaN,Tier 3,Grocery Store,732.3800
1987,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,High,Tier 3,Supermarket Type1,994.7052

In [0]:
data.index

Out[19]: Int64Index([1999, 2009, 1999, 1998, 1987, 2009, 1987, 1985, 2002, 2007,
            ...
            2004, 2002, 2009, 2009, 1997, 1987, 2002, 2004, 2009, 1997],
           dtype='int64', name='Outlet_Establishment_Year', length=8523)

In [0]:
data= pd.read_csv('file:///tmp/datasets/big_mart_sales.csv')

data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [0]:
data_updated = data.set_index('Outlet_Establishment_Year', drop=True, inplace=False)

In [0]:
data_updated.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
Outlet_Establishment_Year,,,,,,,,,,,
1999,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,Medium,Tier 1,Supermarket Type1,3735.1380
2009,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,Medium,Tier 3,Supermarket Type2,443.4228
1999,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,Medium,Tier 1,Supermarket Type1,2097.2700
1998,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,NaN,Tier 3,Grocery Store,732.3800
1987,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,High,Tier 3,Supermarket Type1,994.7052

In [0]:
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

**WILL THE INDEX BE ALWAYS NUMERIC?**

**No, We can also have categorical variable as the index of a dataframe.**

In [0]:
#reset the index
data.set_index('Item_Identifier', drop=True, inplace=True)

In [0]:
# view the top rows of the data
data.head()

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
Item_Identifier,,,,,,,,,,,
FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [0]:
# index of the data

data.index

Out[32]: Index(['FDA15', 'DRC01', 'FDN15', 'FDX07', 'NCD19', 'FDP36', 'FDO10', 'FDP10',
       'FDH17', 'FDU28',
       ...
       'FDH31', 'FDA01', 'FDH24', 'NCJ19', 'FDF53', 'FDF22', 'FDS36', 'NCJ29',
       'FDN46', 'DRG01'],
      dtype='object', name='Item_Identifier', length=8523)

**HOW TO SUBSET THE DATA BASED ON THE LABEL OF THE INDEX?**

- We can subset the data based on the label of the index using the loc function.

In [0]:
data.loc['FDA15']

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
Item_Identifier,,,,,,,,,,,
FDA15,9.3,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
FDA15,9.3,Low Fat,0.016055,Dairy,250.2092,OUT045,2002,NaN,Tier 2,Supermarket Type1,5976.2208
FDA15,9.3,Low Fat,0.016019,Dairy,248.5092,OUT035,2004,Small,Tier 2,Supermarket Type1,6474.2392
FDA15,9.3,Low Fat,0.016088,Dairy,249.6092,OUT018,2009,Medium,Tier 3,Supermarket Type2,5976.2208
FDA15,9.3,Low Fat,0.026818,Dairy,248.9092,OUT010,1998,NaN,Tier 3,Grocery Store,498.0184
FDA15,9.3,Low Fat,0.016009,Dairy,250.6092,OUT013,1987,High,Tier 3,Supermarket Type1,6474.2392
FDA15,NaN,Low Fat,0.015945,Dairy,249.5092,OUT027,1985,Medium,Tier 3,Supermarket Type3,6474.2392
FDA15,9.3,LF,0.016113,Dairy,248.8092,OUT017,2007,NaN,Tier 2,Supermarket Type1,5976.2208

***What if we want to change the back to positional?***

**CAN WE RESET THE THE INDEX?**

***Yes, we can reset the index. Let's see how? We will use the reset_index function.***

In [0]:
# reset the index
data.reset_index(inplace=True)

In [0]:
# view the top rows of the data

data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [0]:
data.index

Out[36]: RangeIndex(start=0, stop=8523, step=1)

**HOW TO SUBSET THE BASED ON A VALUE OF A COLUMN?**

In [0]:
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [0]:
data[data['Item_Type']=='Dairy']

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
11,FDA03,18.500,Regular,0.045464,Dairy,144.1102,OUT046,1997,Small,Tier 1,Supermarket Type1,2187.1530
19,FDU02,13.350,Low Fat,0.102492,Dairy,230.5352,OUT035,2004,Small,Tier 2,Supermarket Type1,2748.4224
28,FDE51,5.925,Regular,0.161467,Dairy,45.5086,OUT010,1998,NaN,Tier 3,Grocery Store,178.4344
30,FDV38,19.250,Low Fat,0.170349,Dairy,55.7956,OUT010,1998,NaN,Tier 3,Grocery Store,163.7868
...,...,...,...,...,...,...,...,...,...,...,...,...
8424,FDC39,7.405,Low Fat,0.159165,Dairy,207.1296,OUT035,2004,Small,Tier 2,Supermarket Type1,3739.1328
8447,FDS26,20.350,Low Fat,0.089975,Dairy,261.6594,OUT017,2007,NaN,Tier 2,Supermarket Type1,7588.1226
8448,FDV50,14.300,Low Fat,0.123071,Dairy,121.1730,OUT018,2009,Medium,Tier 3,Supermarket Type2,2093.9410
8457,FDY50,5.800,Low Fat,0.130931,Dairy,89.9172,OUT035,2004,Small,Tier 2,Supermarket Type1,1516.6924
8512,FDR26,20.700,Low Fat,0.042801,Dairy,178.3028,OUT013,1987,High,Tier 3,Supermarket Type1,2479.4392